import warnings
from tqdm import tqdm
warnings.simplefilter("ignore")
import time
from collections import OrderedDict
import random
import re

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from nltk.tokenize import word_tokenize
import string

from sklearn.manifold import TSNE

# use this section to suppress warning generated by code:
def warn(*args,**kwargs):
    pass

warnings.warn =warn
warnings.filterwarnings('ignore')

def preprocess_string(s):
    #remove all non word characters (everything except numbers and letters) #
    s = re.sub(r"[^\w\s]", '', s)
    #replace all runs of whitespaces with no space
    s= re.sub(r"\s+",'',s)
    #replace digits with no space
    s=re.sub(r"\d",'',s)
    return s
#Taylor Swift Lyrics: "One-Sided Goodbye"
song= """
You said it, then you walked away
But you don't know what goodbye means
Baby, I'm sorry, didn't ever mean to hurt you
Please, save it for a rainy day
'Cause you don't know what crying's like
When the world keeps spinning and I can't take it alone

And you're so different from all those other people
I thought it would be different with you
But I can't see you crying without me
So I guess I'll have to make it through without you

I wasn't ready for your one-sided goodbye
You walked around like you loved me, I
Notice how the world tries to mask that word
"See you later," "gotta go," oh no

I don't care what they would say
If you love someone don't let them go
Do you believe in taking chances?
So tell me why you walked away
'Cause I can't see through your heart
Everything's hazy and you're making me crazy for you

Well, I thought you were different
Maybe I'm crazy
I know I wasn't numb with you
But I can't hear you crying without me
So I guess I'll have to make it through without you

I wasn't ready for your one-sided goodbye
You walked around like you loved me, I
Notice how the world tries to mask that word
"See you later," "gotta go"

Why can't you see, why can't you be
Madly in love with me, too?
Past emotion, but you've already spoken
I guess I'll have to make it through without you

I wasn't ready for your one-sided goodbye
You walked around like you loved me, I
Notice how the world tries to mask that word
"See you later," "gotta go", oh no"""

#Tokenization for FNN
#This PyTorch function is used to obtain a tokenizer for text
from torchtext.data.utils import get_tokenizer
tokenizer = get_tokenizer("basic_english")
tokens = tokenizer(song)


def preprocess_string(s):
    """
    Preprocesses a given string by performing the following steps:

    1. Removes all non-word characters (excluding letters and numbers).
    2. Removes all whitespace characters.
    3. Removes all numeric digits.

    Parameters:
    s (str): The input string to be cleaned.

    Returns:
    str: The processed string with only alphabetic characters, no spaces, and no digits.
    """

    # Remove all non-word characters (everything except letters and numbers)
    # \w matches any word character (letters, numbers, and underscores)
    # \s matches any whitespace characters
    # ^ inside [] negates the selection, so [^\w\s] matches anything that's NOT a word character or whitespace.
    s = re.sub(r"[^\w\s]", '', s)

    # Remove all whitespace characters (spaces, tabs, newlines)
    # \s+ matches one or more whitespace characters.
    s = re.sub(r"\s+", '', s)

    # Remove all digits (0-9)
    # \d matches any digit character.
    s = re.sub(r"\d", '', s)

    return s

def preprocess(words):
    """
    Preprocesses a given text by tokenizing it, cleaning individual words, and
    converting them to lowercase while removing empty or punctuation tokens.

    Steps:
    1. Tokenization: Splits the input text into individual word tokens.
    2. Cleaning: Applies `preprocess_string()` to remove non-word characters,
       spaces, and digits from each token.
    3. Normalization: Converts all tokens to lowercase.
    4. Filtering: Removes empty strings and punctuation tokens.

    Parameters:
    words (str): The input text to be tokenized and preprocessed.

    Returns:
    list: A list of cleaned, lowercase tokens.
    """

    #tokenize the input text into words
    tokens = word_tokenize(words)

    #apply preprocessing to each token (removes unwanted characters)
    tokens = [preprocess_string(w) for w in tokens]

    #convert tokens to lowercase and remove empty strings or punctuation
    return [w.lower() for w in tokens if len(w)!=0 and w not in string.punctuation]

tokens =preprocess(song)

#print(tokens)

#Indexing
# TorchText provides tools to tokenize text into individual words (tokens) and build a vocabulary,
# which maps tokens to unique integer indexes.
# This is a crucial step in preparing text data for machine learning models that require numerical input.
from collections import Counter
from torchtext.vocab import Vocab

def tokenizetext(song):
    """
     Tokenizes the input text (song) and builds a vocabulary from the tokens.

     Steps:
     1. Tokenization: The function splits the input text into words and applies
        a tokenizer function to each word.
     2. Vocabulary Building: Constructs a vocabulary from the tokenized words,
        including a special "<unk>" token to handle out-of-vocabulary words.
     3. Default Indexing: Sets the default index for unknown words, ensuring
        that any unseen tokens are mapped to "<unk>".

     Parameters:
     song (str): The input text (song lyrics) to be tokenized and processed.

     Returns:
     vocab (Vocab): A vocabulary object mapping tokens to their corresponding indices.
     """

    #tokenize the text
    #split the input text into words and apply the tokenizer function to each word
    #the map function ensures that each word is tokenized properly

    tokenized_song = map(tokenizer, song.split())

    #Build vocabulary from tokenized text
    #the function build_vocab from iterator constructs a vocab by iterating
    #over the tokenized words. The special token <unk> is added to  handle words that are not present in the vocab
    counter = Counter()
    for tokens in tokenized_song:
        counter.update(tokens)

    #vocab = build_vocab_from_iterator(tokenized_song,specials=["<unk>"]) cant use because torch text 0.8 doesn't support
    vocab = Vocab(counter, specials=['<unk>'])
    #set the default index for unknown words , the default index is set to the index of <unk> so that the any word not found
    #in the vocab is mapped to this token , preventing errors during lookup
    unk_token = '<unk>'
    unk_idx = vocab.stoi[unk_token]

    #vocab.set_default_index(vocab["<unk>"]) cant use because torch text 0.8 doesn't support
    vocab.stoi.default_factory = lambda: unk_idx

    return vocab

#convert the tokens to indices by applying the func
vocab = tokenizetext(song)
#vocab(tokens[0:10])
#a text function that converts raw text into indexes
#tokens[0:10]
#text_pipeline=lambda x: vocab(tokenizer(x))
#text_pipeline(song)[0:10]

index_to_token = vocab.itos
#index_to_token[58]

def genembedding(vocab):
    """
     Generates an embedding layer for the given vocabulary.

     The embedding layer transforms words into dense vector representations,
     allowing the model to learn semantic relationships between words.

     Parameters:
     vocab (Vocab): The vocabulary object containing unique words and their indices.

     Returns:
     nn.Embedding: A PyTorch embedding layer with a specified embedding dimension.
     """

    #define the embedding dimension (size of word vectors)
    embedding_dim = 20 #each word will be rep as a 20 dim vector

    #get the vocab size (number of unique words in the vocab)
    vocab_size = len(vocab)
    #create an embedding layer
    #the nn.embedding module maps word indices to dense vector rep
    # it takes vocab_size as the number of words and embedding _dim as the vector size

    embeddings = nn.Embedding(vocab_size,embedding_dim)
    return embeddings

embeddings = genembedding(vocab)
for n in range(2):
    embedding = embeddings(torch.tensor(n))
    #print("word", index_to_token[n])
    #print("index", n)
    #print("embedding", embedding)
    #print("embedding shape", embedding.shape)

#Generating context-target pairs (n-grams) Organize words within a variable-size context using
#the following approach: Each word is denoted by 'i'. To establish the context, simply subtract 'j'. The size of the context is determined by the value ofCONTEXT_SIZE.

CONTEXT_SIZE = 2 # num of previous words used to predict the next word

def genngrams(tokens):
    """
      Generates n-grams from a list of tokens, where each n-gram consists of a
      context (previous words) and a target (next word).

      The function constructs a list of tuples where:
      - The first element is a list of `CONTEXT_SIZE` previous words.
      - The second element is the target word that follows the context.

      Parameters:
      tokens (list): A list of preprocessed word tokens.

      Returns:
      list: A list of tuples representing n-grams.
            Each tuple contains (context_words, target_word).
      """
    #generate n grams
    #iterate thru the tokens starting from index CONTEXT_SIZE to the end
    #for each token at position 'i' , extract the previous CONTEXT_SIZE words as context
    ngrams=[
        (
            [tokens[i-j-1] for j in range(CONTEXT_SIZE)],
            tokens[i] #target word - the word to predict
        )
        for i in range(CONTEXT_SIZE, len(tokens))


    ]
    return ngrams

#generate n grams
ngrams = genngrams(tokens)
context,target = ngrams[0]
#print("context", context)
#print("target", target)
#print("context index", [vocab[token] for token in context],"target_index",[vocab[token] for token in target])

#there In this context, there are multiple words.
# Aggregate the embeddings of each of these words and then adjust the input size of the subsequent layer accordingly. Then, create the next layer
embedding_dim =20
linear =nn.Linear(embedding_dim*CONTEXT_SIZE,128)

embeddings =genembedding(vocab)
# Convert tokens to a list of indices using a list comprehension,
# then pass that list to the tensor
context_indices = [vocab[token] for token in context]
my_embeddings = embeddings(torch.tensor(context_indices))
my_embeddings.shape

#reshape the embeddings
my_embeddings = my_embeddings.reshape(1,-1)
my_embeddings.shape
#now use it as inputs to next layer
linear(my_embeddings)

#Batch function Create a Batch function to interface with the data loader.
# Several adjustments are necessary to handle words that are part of a context in one batch and a predicted word in the following batch.

from torch.utils.data import DataLoader # Importing DataLoader for batch processing
import torch

device =torch.device("cuda" if torch.cuda.is_available() else "cpu")
#define hyperparameters
CONTEXT_SIZE = 3 #number of previous words used as context for prediction
BATCH_SIZE = 10 # number of samples per training batch
EMBEDDING_DIM=10 #dimension of word embeddings

def collate_batch(batch):
    """
    Processes a batch of text data into input (context) and output (target) tensors
    for training a language model.

    The function extracts:
    - `context`: A list of word indices representing the context words for each target word.
    - `target`: A list of word indices representing the target word to predict.

    Parameters:
    batch (list): A list of tokenized words (strings).

    Returns:
    tuple: Two PyTorch tensors: (context_tensor, target_tensor)
           - context_tensor: Tensor of shape (batch_size - CONTEXT_SIZE, CONTEXT_SIZE),
             containing the word indices of context words.
           - target_tensor: Tensor of shape (batch_size - CONTEXT_SIZE,),
             containing the word indices of target words.
    """
    batch_size = len(batch) #get the size of the batch
    context,target = [],[] # init the lists for context and target words

    #loop thru the batch, ensuring enough previous words exist for context

    for i in range(CONTEXT_SIZE,batch_size):
        #convert the target word to its index using the vocab
        target.append(vocab[batch[i]])

        #convert the prev CONTEXT_SIZE words to indices using the vocab
        context_indices = [vocab[batch[i-j-1]] for j in range(CONTEXT_SIZE)]
        context.append(context_indices)
    #convert lists to Pytorch tensors and move them to appr device
    return torch.tensor(context).to(device), torch.tensor(target).to(device)

"""Similarly, it's important to highlight that the size of the last batch could deviate from that of the earlier batches. 
To tackle this, the approach involves adjusting the final batch to conform to the specified batch size, ensuring it becomes a multiple of the predetermined size.
 When necessary, you'll employ padding techniques to achieve this harmonization. One approach you'll use is appending the beginning of the song to the end of the batch."""

Padding = BATCH_SIZE -len(tokens)%BATCH_SIZE
tokens_pad = tokens+tokens[0:Padding]
dataloader =DataLoader(tokens_pad,batch_size= BATCH_SIZE,shuffle=False,collate_fn=collate_batch)


#Multi-class neural network You have developed a PyTorch class for a multi-class neural network.
# The network's output is the probability of the next word within a given context.
# Therefore, the number of classes corresponds to the count of distinct words.
# The initial layer consists of embeddings, and in addition to the final layer, an extra hidden layer is incorporated.

class NgramLanguageModeler(nn.Module):
    """
     A neural network-based n-gram language model that predicts the next word
     given a sequence of context words.

     This model consists of:
     - An embedding layer that converts word indices into dense vector representations.
     - A fully connected hidden layer with ReLU activation.
     - An output layer that predicts the probability distribution over the vocabulary.

     Parameters:
     vocab_size (int): The number of unique words in the vocabulary.
     embedding_dim (int): The size of the word embeddings (vector representation of words).
     context_size (int): The number of previous words used as context to predict the next word.
     """

    def __init__(self,vocab_size,embedding_dim,context_size):
        super(NgramLanguageModeler,self).__init__()

        #store context size and embedding dimension
        self.context_size = context_size
        self.embedding_dim= embedding_dim

        #embedding layer: , maps word indices to dense vectors
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)

        #fully connected hidden layer:maps the concatenated embeddings to a 128 dimensional space
        self.linear1 = nn.Linear(context_size*embedding_dim,128)

        #output layer: maps the hidden layer output to vocabulary size (probability dist over words)
        self.linear2 = nn.Linear(128,vocab_size)

    def forward(self,inputs):
            """
                  Forward pass of the model.

                  Parameters:
                  inputs (Tensor): A tensor of shape (batch_size, context_size) containing word indices.

                  Returns:
                  Tensor: A tensor of shape (batch_size, vocab_size) representing predicted probabilities for the next word.
                  """
            #convert input word indices into dense vectors using the embedding layer
            embeds = self.embeddings(inputs) #shape : batch _size, context size, embedding dim

            #reshape the embeddings into a single vector per input sample
            embeds = torch.reshape (embeds,(-1,self.context_size*self.embedding_dim))
            #new shape: (batch_size,context size * embedding dim)
            #apply first fully connected layer with RELU activation
            out =F.relu(self.linear1(embeds))#shape - batchsize ,128
            #apply second fully connected layer to generate vocab size logits
            out = self.linear2(out) #shape : (batch size, vocab size)
            return out



#create a model
model = NgramLanguageModeler(len(vocab),EMBEDDING_DIM,CONTEXT_SIZE).to(device)

#retrieve samples from the data loader obj and input into the neural nw

context,target = next(iter(dataloader))
print(context,target)

out = model(context)

def write_song(model,my_song,num_of_words =100,temperature=1.0):
    """
     Generates text using a trained n-gram language model.

     Given an initial text (`my_song`), the function generates additional words by
     predicting the next word iteratively based on the trained model.

     Parameters:
     model (nn.Module): The trained n-gram language model.
     my_song (str): The initial seed text to start generating words.
     number_of_words (int): The number of words to generate (default: 100).

     Returns:
     str: The generated song lyrics as a string.
     """
    #get the mapping from index to word for decoding predictions
    index_to_token = vocab.itos
    generated_tokens = preprocess(my_song)
    #loop to generate the desired num of words
    for i in range(num_of_words):
        with torch.no_grad(): #disable gradient computation for inference
            #prepare the input context by extracting the last CONtext size words from tokens
            context_indices = [vocab[tokens[-(j+1)]] for j in range(CONTEXT_SIZE)]
            context = torch.tensor(context_indices).to(device)
            logits = model(context.unsqueeze(0))
            #temperature scaling -lower = more  conservative , higher = more creative
            scaled_logits = logits / temperature

            #context =torch.tensor(
             #   vocab([tokens[i-j-1] for j in range(CONTEXT_SIZE)])
              #  ).to(device)
            #predict the next word by selecting the word with the highest prob
            probs = torch.softmax(scaled_logits, dim=-1)
            #sample from distribution instead of always picking the top word
            word_idx = torch.multinomial(probs, num_samples=1).item()
            predicted_word = index_to_token[word_idx]

            #append the predicted word to the generated text
            generated_tokens.append(predicted_word)
            my_song += " " + predicted_word

    return my_song #return the generated lyrics

#print(write_song(model,song))


def pickrandomline(song):
    """
    Selects a random line from the given song text.

    This function splits the song into separate lines and randomly picks one of them.

    Parameters:
    song (str): The song lyrics as a multi-line string.

    Returns:
    str: A randomly selected line from the song.
    """

    #split the song into individual lines
    lines = song.split("\n")

    #randomly select a line and remove leading/trailing whitespace
    selected_line = random.choice(lines).strip()
    return selected_line

#Training model
#Training a language model involves a multi-step process that leverages training and testing data to optimize model performance.
# In the realm of Natural Language Processing (NLP), this process often employs various metrics to gauge a model's accuracy,
# such as perplexity or accuracy on unseen data. However, in the context of your current exploration,
# you will embark on a slightly different journey. Instead of relying solely on conventional NLP metrics, the focus shifts to manual inspection of the results.
# You have the cross entropy loss between input logits and target:
criterion =torch.nn.CrossEntropyLoss() # the cross entropy loss between input logits and target

def train(dataloader,model,song,number_of_epochs=100,show=10):
    """
      Args:
          dataloader (DataLoader): DataLoader containing training data.
          model (nn.Module): Neural network model to be trained.
          number_of_epochs (int, optional): Number of epochs for training. Default is 100.
          show (int, optional): Interval for displaying progress. Default is 10.

      Returns:
          list: List containing loss values for each epoch.
      """
    MY_LOSS =[]# list to store loss values for each epoch

    #iterate over the specified number of epochs
    for epoch in tqdm (range(number_of_epochs)):
        total_loss=0# init total loss for current epoch
        my_song =""# inita string to store the generated song

        #iterate over batches in the data loader
        for context,target in dataloader:
            model.zero_grad() #zero the gradients to avoid accumulation
            predicted =model(context) # forward pass thru the model to get predictions
            loss = criterion(predicted,target.reshape(-1)) # calculate the loss
            total_loss +=loss.item() # accumulate the loss
            loss.backward() #backpropogation to compute gradients
            optimizer.step() #update the model parameters using the optimizer
        #display progress and generate the song at specified intervals
        if epoch % show ==0:
            selected_line = pickrandomline(song)
            my_song += write_song(model,selected_line) #generate song using the model

            print("Generated Song:")
            print("\n")
            print(my_song)

        MY_LOSS.append(total_loss/len(dataloader)) # append the total loss for the epoch to MY_LOSS list

    return MY_LOSS #return the list of mean loss values for each epoch
my_loss_list =[]

#define the context size of the n gram model
CONTEXT_SIZE = 2

#create an instance of the NGramLanguage Modeler class with specified parameters
model_2 = NgramLanguageModeler(len(vocab),EMBEDDING_DIM,CONTEXT_SIZE).to(device)

#define the optimizer for training the model using the Stochastic gradient descent (SGD)
optimizer = optim.SGD(model_2.parameters(),lr=0.01)

#set up a learning rate scheduler using Step LR to adjust the learning rate during training
scheduler = torch.optim.lr_scheduler.StepLR(optimizer,step_size = 1.0,gamma= 0.1)

#train the model 2
my_loss= train(dataloader,model_2,song)

#save the model
save_path ='2gram.pth'
torch.save(model_2.state_dict(),save_path)
my_loss_list.append(my_loss)

#The code provided below shows word embeddings from the created model, reduces their dimensionality to 2D using t-SNE, and then plots them as a scatter plot.
# Additionally, it annotates the first 20 points in the visualization with their corresponding words.
# This is used to visualize how similar words cluster together in a lower-dimensional space, revealing the structure of the word embeddings.
# Embeddings allow the model to represent words in a continuous vector space, capturing semantic relationships and similarities between words

X = model_2.embeddings.weight.cpu().detach().numpy()
tsne = TSNE(n_components=2,random_state=42)
X_2d =tsne.fit_transform(X)

labels = []
for j in range (len(X_2d)):
    if j< 20 :
        plt.scatter(X_2d[j,0],X_2d[j,1], label= index_to_token[j])
        labels.append(index_to_token[j])
        #add owords as annotations
        plt.annotate(index_to_token[j],
                     (X_2d[j,0],X_2d[j,1]),
                     textcoords='offset points',
                     xytext=(0,10),
                     ha='center')
    else:
        plt.scatter(X_2d[j,0],X_2d[j,1])

plt.legend(labels,loc='upper left',bbox_to_anchor=(1,1))
plt.show()

import numpy as np
print(np.__version__)


#4 GRAM MODEL
CONTEXT_SIZE=4
model_4 = NgramLanguageModeler(len(vocab), EMBEDDING_DIM, CONTEXT_SIZE).to(device)
optimizer = optim.SGD(model_4.parameters(), lr=0.01)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1.0, gamma=0.1)
my_loss=train(dataloader,model_4,song)

save_path = '4gram.pth'
torch.save(model_4.state_dict(), save_path)

my_loss_list.append(my_loss)

X = model_4.embeddings.weight.cpu().detach().numpy()
tsne = TSNE(n_components=2,random_state=42)
X_2d =tsne.fit_transform(X)

labels = []
for j in range (len(X_2d)):
    if j< 20 :
        plt.scatter(X_2d[j,0],X_2d[j,1], label= index_to_token[j])
        labels.append(index_to_token[j])
        #add owords as annotations
        plt.annotate(index_to_token[j],
                     (X_2d[j,0],X_2d[j,1]),
                     textcoords='offset points',
                     xytext=(0,10),
                     ha='center')
    else:
        plt.scatter(X_2d[j,0],X_2d[j,1])

plt.legend(labels,loc='upper left',bbox_to_anchor=(1,1))
plt.show()


#8 GRAM MODEL

CONTEXT_SIZE=8
model_8 = NgramLanguageModeler(len(vocab), EMBEDDING_DIM, CONTEXT_SIZE).to(device)
optimizer = optim.SGD(model_8.parameters(), lr=0.01)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1.0, gamma=0.1)
my_loss=train(dataloader,model_8,song)

save_path = '8gram.pth'
torch.save(model_8.state_dict(), save_path)

my_loss_list.append(my_loss)

X = model_8.embeddings.weight.cpu().detach().numpy()
tsne = TSNE(n_components=2,random_state=42)
X_2d =tsne.fit_transform(X)

labels = []
for j in range (len(X_2d)):
    if j< 20 :
        plt.scatter(X_2d[j,0],X_2d[j,1], label= index_to_token[j])
        labels.append(index_to_token[j])
        #add owords as annotations
        plt.annotate(index_to_token[j],
                     (X_2d[j,0],X_2d[j,1]),
                     textcoords='offset points',
                     xytext=(0,10),
                     ha='center')
    else:
        plt.scatter(X_2d[j,0],X_2d[j,1])

plt.legend(labels,loc='upper left',bbox_to_anchor=(1,1))
plt.show()

#When considering the plotted loss for each model, a discernible trend emerges:
# an increase in context size correlates with a reduction in loss. While this specific approach
# lacks the inclusion of model validation or the utilization of conventional NLP evaluation metrics, the visual evidence substantiates its superior performance.
print("PLOT for LOSS ")
for (my_loss,model_name) in zip(my_loss_list,["2-gram","4-gram","8-gram"]):
    plt.plot(my_loss,label = "cross-entropy loss - {}".format(model_name))
    plt.legend()
    plt.show()

#PERPLEXITY
#A lower perplexity value indicates that the model is more confident and accurate in predicting the data. Conversely, a higher perplexity suggests that the model is less certain and less accurate in its predictions.

#Perplexity can be seen as an estimate of the average number of choices the model has for the next word or event in a sequence.
# A lower perplexity means that the model is more certain about the next word, while a higher perplexity means that there are more possible choices.

for (my_loss,model_name) in zip(my_loss_list,["2-gram","4-gram","8-gram"]):
    #calcuclate the perplexity using the loss
    perplexity = np.exp(my_loss)
    plt.plot(perplexity,label="Perplexity - {}".format(model_name))
    plt.legend()
    plt.xlabel("Epoch")
    plt.ylabel("Perplexity")
    plt.title("Perplexity by Context Size")
    plt.legend()
    plt.show()

